---
language: python
services: docker

install:
  # Install test dependencies.
  - pip install ansible molecule docker

script:
  - . .env/bin/activate
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
