---
# Debian based OS
- name: Rundeck | Install supporting packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - python-pip
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | Install supporting python packages
  pip:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - httplib2
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | Add Bintray GPG key for rundeck repo
  apt_key:
    id: 379CE192D401AB61
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | Add Rundeck Build GPG key
  apt_key:
    id: 85E9DBC74FCB329EDEDADD2E90770E1BE2D1065B
    url: http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | Add Rundeck APT repository on Bintray
  apt_repository:
    repo: 'deb http://dl.bintray.com/rundeck/rundeck-deb /'
    filename: rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | install from APT repository
  apt:
    name: rundeck
    state: present
    allow_unauthenticated: yes #FIXME: https://github.com/rundeck/rundeck/issues/93
  notify:
    - systemd daemon-reload
    - restart rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | check upstart configuration exists
  register: upstart_config
  stat:
    path: /etc/init/rundeckd.conf
    get_md5: no
    get_checksum: no
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | remove System V init.d script if upstart config exists
  file:
    path: /etc/init.d/rundeckd
    state: absent
  when: upstart_config.stat.exists
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | add systemd service helper
  copy:
    src: systemd/rundeck-start
    dest: /usr/bin/rundeck-start
    owner: root
    group: root
    mode: 0755
  when: ansible_service_mgr == 'systemd'
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | add systemd service unit
  copy:
    src: systemd/rundeckd.service
    dest: /etc/systemd/system/rundeckd.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  notify:
    - systemd daemon-reload
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | ensure service log directory has correct ownership
  file:
    path: /var/log/rundeck
    owner: rundeck
    state: directory
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | See if there are more log files
  find:
    paths: /var/log/rundeck
    file_type: file
    patterns: "*.log"
  register: rundeck_logfiles
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | ensure service log files have correct ownership
  file:
    path: "{{ item.path }}"
    owner: rundeck
    state: file
  with_items:
    "{{ rundeck_logfiles.files }}"
  tags:
    - rundeck
    - install
    - packages
