---
# Redhat based OS
- name: Rundeck | get rundeck rpm
  yum:
    name: http://repo.rundeck.org/latest.rpm
    state: present
  become: yes
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | get rundeck rpm
  yum:
    name: rundeck
    state: present
  become: yes
  notify:
    - start rundeck
  tags:
    - rundeck
    - install
    - packages

- name: install redhat | ensure dependencies are installed
  package:
    name:
      -  libsemanage-python
    state: installed
  tags:
    - rundeck
    - install
    - selinux

- name: install redhat | ensure nginx can communicate to jenkins
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  tags:
    - rundeck
    - install
    - selinux
