---
# Redhat based OS
- name: Redhat installation | add python 2.x.x dependencies
  pip:
    name: ['urllib3', 'pyOpenSSL', 'ndg-httpsclient', 'pyasn1']
  when: ansible_python_version is version('2.7', '<')
  tags:
    - rundeck
    - install
    - packages

- name: Redhat installation | set rundeck rpm
  yum:
    name: http://repo.rundeck.org/latest.rpm
    state: present
  become: true
  tags:
    - rundeck
    - install
    - packages

- name: Redhat installation | get rundeck rpm
  yum:
    name: rundeck
    state: present
  become: true
  notify:
    - start rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Redhat installation | check is getenforce installed
  shell: command -v getenforce >/dev/null 2>&1
  register: is_getenforce_exist
  changed_when: false
  ignore_errors: true
# this task runs 'getenforce' and registers the result into the "sestatus" variable
# changed_when: false tells ansible never to mark this task as "changed"
- name: Redhat installation | test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
  when: is_getenforce_exist.rc == 0

- name: Redhat installation | ensure dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  when: is_getenforce_exist.rc == 0 and sestatus is defined and "Enabled" in sestatus.stdout
  with_items:
    - libsemanage-python
    - libselinux-python
  tags:
    - rundeck
    - install
    - selinux

- name: Redhat installation | ensure nginx can communicate to rundeck
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: is_getenforce_exist.rc == 0 and sestatus is defined and "Enabled" in sestatus.stdout
  tags:
    - rundeck
    - install
    - selinux
