---
# extras
- name: download rundeck plugins
  get_url:
    dest: /var/lib/rundeck/libext/{{ item.split('/')|last }}
    url: {{ item }}
  with_items: "{{ rundeck_plugins }}"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - plugins