# -*- mode: ruby -*-
# vi: set ft=ruby :

IP_ADDRESS = "33.33.33.68"
HTTP_PORT  = 8068
HTTPS_PORT = 8468

PLAYBOOK = ENV['PLAYBOOK'] || 'default_test.yml'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  ## identifier
  config.vm.hostname = "vagrant-ansible-rundeck-trusty64"
  ## Network
  config.vm.network "private_network", ip: IP_ADDRESS
  config.vm.network "forwarded_port", guest: 4440, host: HTTP_PORT  # Web server
  config.vm.network "forwarded_port", guest: 443, host: HTTPS_PORT # Secure web server
  ## virtual box specification
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    v.customize ["modifyvm", :id, "--memory", 1024]
  end
  ## Provision via ansible using the defaults:
  config.vm.provision "ansible" do |ansible|
    ansible.extra_vars = {
      environment: "vagrant",
      rundeck_domain: "localhost:8068",
      java_packages: [ "openjdk-7-jre-headless" ]
    }
    ansible.groups = {
      "rundeck-servers" => [ "default" ]
    }
    ansible.playbook = "../#{PLAYBOOK}"
    ansible.host_key_checking = false
    ansible.verbose = "v"
    # use ANSIBLE_KEEP_REMOTE_FILES=1 to debug execution
  end
end
